[package]
name = "onie-sai-rpc"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.2.0"
ttrpc = "0.8.1"

[build-dependencies]
ttrpc-codegen = "0.4.2"
