[workspace]
resolver = "2"
members = [
    "sai-sys",
    "sai",
    "xcvr-sys",
    "xcvr",
    "xcvr-dell-s5200",
    "xcvrctl",
    "onie-sai-rpc",
    "onie-sai",
    "onie-sai-common",
    "onie-said",
    "onie-saictl",
    "onie-lldp",
]
