[package]
name = "xcvr-dell-s5200"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
xcvr-sys = { version = "0.1.0", path = "../xcvr-sys" }
