
---
device:
    0:
        DEVICE_CONFIG:
            # CORE CLOCK FREQUENCY
            CORE_CLK_FREQ: CLK_1350MHZ
            # PP CLOCK FREQUENCY
            PP_CLK_FREQ: CLK_1350MHZ
            VARIANT: DNA_4_11_4_0
...
---
bcm_device:
    0:
        global:
            # uft_mode: 1
            pktio_mode: 1
            # l3_aplm_template: 1
            # l2_learn_enable: 1
            vlan_flooding_l2mc_num_reserved: 0
            ipv6_lpm_128b_enable: 1
            shared_block_mask_section: uc_bc
            skip_protocol_default_entries: 1
            # cls_cmd_daemon: 1
            sai_feat_tail_timestamp: 1
            sai_port_phy_time_sync_en: 1
            sai_field_group_auto_prioritize: 1
            sai_tunnel_support: 1
            multi_network_groups: 1
            l3_alpm_template: 1
            l3_alpm_hit_skip: 1
            sai_nbr_bcast_ifp_optimized: 1
            use_all_splithorizon_groups: 1
            riot_enable: 1
            riot_overlay_l3_intf_mem_size: 8192
            riot_overlay_l3_egress_mem_size: 32768
            l3_ecmp_levels: 2
            riot_overlay_ecmp_resilient_hash_size: 16384
            sai_port_queue_ecn_counter: 1
            pfc_deadlock_seq_control : 1
            sai_verify_incoming_chksum: 0
            ipmc_age_mode: 1
            flexctr_action_reserved_ipmc_hitbit: 1
...
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP: 0x45
                TX_POLARITY_FLIP: 0xAA
                RX_LANE_MAP: 0x01376425
                TX_LANE_MAP: 0x30641275
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0xAA
                TX_POLARITY_FLIP: 0x6B
                RX_LANE_MAP: 0x07561243
                TX_LANE_MAP: 0x06137524
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x44
                TX_POLARITY_FLIP: 0x33
                RX_LANE_MAP: 0x01376425
                TX_LANE_MAP: 0x41635072
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0          
                RX_POLARITY_FLIP: 0x80
                TX_POLARITY_FLIP: 0x5F
                RX_LANE_MAP: 0x07561243
                TX_LANE_MAP: 0x05137624
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0xC5
                RX_LANE_MAP: 0x45623170
                TX_LANE_MAP: 0x52163704
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x7F
                TX_POLARITY_FLIP: 0x1C
                RX_LANE_MAP: 0x42135607
                TX_LANE_MAP: 0x70632154
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0x45
                RX_LANE_MAP: 0x45632071
                TX_LANE_MAP: 0x52163704
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0x7F
                TX_POLARITY_FLIP: 0x45
                RX_LANE_MAP: 0x42135607
                TX_LANE_MAP: 0x61370254
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xBA
                TX_POLARITY_FLIP: 0x9C
                RX_LANE_MAP: 0x47632150
                TX_LANE_MAP: 0x64152703
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xA0
                TX_POLARITY_FLIP: 0x2
                RX_LANE_MAP: 0x04651372
                TX_LANE_MAP: 0x05176432
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x44
                TX_POLARITY_FLIP: 0x2F
                RX_LANE_MAP: 0x37041625
                TX_LANE_MAP: 0x07516342
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x3B
                TX_POLARITY_FLIP: 0xEA
                RX_LANE_MAP: 0x16073425
                TX_LANE_MAP: 0x46057213                   
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0x68
                RX_LANE_MAP: 0x47601352
                TX_LANE_MAP: 0x34165207
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0x7F
                TX_POLARITY_FLIP: 0xEB
                RX_LANE_MAP: 0x60137524
                TX_LANE_MAP: 0x51403627
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0xBF
                RX_LANE_MAP: 0x47632051
                TX_LANE_MAP: 0x03254617

            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP: 0x80
                TX_POLARITY_FLIP: 0xDA
                RX_LANE_MAP: 0x24753061
                TX_LANE_MAP: 0x17065432
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0x0
                RX_LANE_MAP: 0x47610352
                TX_LANE_MAP: 0x43072615
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x80
                TX_POLARITY_FLIP: 0x85
                RX_LANE_MAP: 0x14750362
                TX_LANE_MAP: 0x37614520
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x44
                TX_POLARITY_FLIP: 0x27
                RX_LANE_MAP: 0x30145726
                TX_LANE_MAP: 0x17603254
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0x80
                TX_POLARITY_FLIP: 0x2A
                RX_LANE_MAP: 0x07361524
                TX_LANE_MAP: 0x06517234   
            ?
                PC_PM_ID: 29
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xDB
                TX_POLARITY_FLIP: 0x8D
                RX_LANE_MAP: 0x74610253
                TX_LANE_MAP: 0x23174605
            ?
                PC_PM_ID: 30
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0x5D
                TX_POLARITY_FLIP: 0x54
                RX_LANE_MAP: 0x52034617
                TX_LANE_MAP: 0x63725140
            ?
                PC_PM_ID: 31
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0x7E
                RX_LANE_MAP: 0x47326150
                TX_LANE_MAP: 0x04251637
            ?
                PC_PM_ID: 32
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x80
                TX_POLARITY_FLIP: 0xCE
                RX_LANE_MAP: 0x25743160
                TX_LANE_MAP: 0x06327514 

            ?
                PC_PM_ID: 21
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x44
                TX_POLARITY_FLIP: 0x40
                RX_LANE_MAP: 0x03154627
                TX_LANE_MAP: 0x45127063
            ?
                PC_PM_ID: 22
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0x80
                TX_POLARITY_FLIP: 0x6D
                RX_LANE_MAP: 0x25743160
                TX_LANE_MAP: 0x37126405
            ?
                PC_PM_ID: 23
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0           
                RX_POLARITY_FLIP: 0x44
                TX_POLARITY_FLIP: 0x58
                RX_LANE_MAP: 0x03154627
                TX_LANE_MAP: 0x45126073
            ?
                PC_PM_ID: 24
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x80
                TX_POLARITY_FLIP: 0xCC
                RX_LANE_MAP: 0x25743160
                TX_LANE_MAP: 0x07326415  

            ?
                PC_PM_ID: 25
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0xD
                RX_LANE_MAP: 0x47510362
                TX_LANE_MAP: 0x36250714
            ?
                PC_PM_ID: 26
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x7F
                TX_POLARITY_FLIP: 0xF3
                RX_LANE_MAP: 0x61307524
                TX_LANE_MAP: 0x71450263
            ?
                PC_PM_ID: 27
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0xBB
                TX_POLARITY_FLIP: 0x8B
                RX_LANE_MAP: 0x47601352
                TX_LANE_MAP: 0x34251706
            ?
                PC_PM_ID: 28
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0            
                RX_POLARITY_FLIP: 0x7F
                TX_POLARITY_FLIP: 0x41
                RX_LANE_MAP: 0x60217534
                TX_LANE_MAP: 0x71460352

...
---
device:
    0:        
        PC_PORT_PHYS_MAP:
            ?
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 43
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 25                 
            ?
                PORT_ID: 60
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 61
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 80
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 81
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 82
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 83
            :
                PC_PHYS_PORT_ID: 153
            ?
                PORT_ID: 140
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 141
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 142
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 143
            :
                PC_PHYS_PORT_ID: 249
            ?
                PORT_ID: 100
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 101
            :
                PC_PHYS_PORT_ID: 169
            ?
                PORT_ID: 102
            :
                PC_PHYS_PORT_ID: 177
            ?
                PORT_ID: 103
            :
                PC_PHYS_PORT_ID: 185
            ?
                PORT_ID: 120
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 121
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 122
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 123
            :
                PC_PHYS_PORT_ID: 217
            ?
               # management port
                PORT_ID: 78
            :
                PC_PHYS_PORT_ID: 258
            ?
                # management port
                PORT_ID: 158
            :
                PC_PHYS_PORT_ID: 260
            ?
               # management port
                PORT_ID: 38
            :
                PC_PHYS_PORT_ID: 257
            ?
               # management port
                PORT_ID: 118
            :
                PC_PHYS_PORT_ID: 259


...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[20,23],[40,43],[1,4],[60,63],[80,83],[140,143],[100,103],[120,123]]
            :
                &port_mode_400g
                ENABLE: 1
                SPEED: 400000
                NUM_LANES: 8
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
                LINK_TRAINING : 1
            ?
                PORT_ID: [78,158,38,118]
            :
                &port_mode_10g_xfi
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
                MAX_FRAME_SIZE: 9416                

...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 0
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0

        # Per pipe flex state configuration
        #FLEX_STATE_CONFIG:
        #    FLEX_STATE_ING_OPERMODE_PIPEUNIQUE: 0
        #    FLEX_STATE_EGR_OPERMODE_PIPEUNIQUE: 1

        # Lossy vs Lossless mode
        TM_THD_CONFIG:
            THRESHOLD_MODE: LOSSLESS

        # IFP mode
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...
---
device:
    0:
        TM_SCHEDULER_CONFIG:
            NUM_MC_Q: NUM_MC_Q_4
...  
