#
# BCM56780 20x400g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        SEC_CONFIG:
            SEC_ENABLE: 0
...
---
device:
    0:
        DEVICE_CONFIG:
            # CORE CLOCK FREQUENCY
            CORE_CLK_FREQ: CLK_1350MHZ
            # PP CLOCK FREQUENCY
            PP_CLK_FREQ: CLK_1350MHZ
            #VARIANT: INA_2_5_19
            VARIANT: DNA_2_9_5_0
...
---

device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 24
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 43
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 44
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 60
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 61
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 64
            :
                PC_PHYS_PORT_ID: 153
            ?
                # management port
                PORT_ID: 38
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 78
            :
                PC_PHYS_PORT_ID: 162
            ?
               # loopback port
                PORT_ID: 39
            :
                PC_PHYS_PORT_ID: 163
            ?
                PORT_ID: 79
            :
                PC_PHYS_PORT_ID: 164
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[1, 5],
                          [20, 24],
                          [40, 44],
                          [60, 64]]
            :
                &port_mode_400g
                ENABLE: 0
                SPEED: 400000
                NUM_LANES: 8
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
            ?
                PORT_ID: [39,     # loopback port 0 (Pipe 1)
                          79]     # loopback port 1 (Pipe 3)
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [38,     # Management port 0 (Pipe 1)
                          78]     # Management port 1 (Pipe 3)
            :
                &port_mode_10g_xfi
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
                MAX_FRAME_SIZE: 9416
...
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03652147
                TX_LANE_MAP: 0x47216503
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47152036
                TX_LANE_MAP: 0x21450367
                RX_POLARITY_FLIP: 0x7c
                TX_POLARITY_FLIP: 0x65
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x76105432
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0x65
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x76105432
                TX_LANE_MAP: 0x67014532
                RX_POLARITY_FLIP: 0x30
                TX_POLARITY_FLIP: 0x3f
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67014523
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10753264
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0x3f
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01572346
                TX_LANE_MAP: 0x67105432
                RX_POLARITY_FLIP: 0x95
                TX_POLARITY_FLIP: 0xc0
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01572346
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0xc0
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x76420531
                TX_LANE_MAP: 0x46015723
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x60
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67014523
                TX_LANE_MAP: 0x67014523
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01672345
                TX_LANE_MAP: 0x67014523
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x42763105
                TX_LANE_MAP: 0x46015723
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x64
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x57014623
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x57014623
                TX_LANE_MAP: 0x67105432
                RX_POLARITY_FLIP: 0xcf
                TX_POLARITY_FLIP: 0xc0
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x75106432
                TX_LANE_MAP: 0x10673254
                RX_POLARITY_FLIP: 0x65
                TX_POLARITY_FLIP: 0xcf
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01672345
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0xc0
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10763254
                TX_LANE_MAP: 0x67014532
                RX_POLARITY_FLIP: 0x6a
                TX_POLARITY_FLIP: 0x3f
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10763254
                TX_LANE_MAP: 0x01673245
                RX_POLARITY_FLIP: 0x3f
                TX_POLARITY_FLIP: 0x30
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x15473620
                TX_LANE_MAP: 0x45216703
                RX_POLARITY_FLIP: 0x0c
                TX_POLARITY_FLIP: 0x6a
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x65034721
                TX_LANE_MAP: 0x21470365
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xff
            ?
                PC_PM_ID: 21
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x3210
                TX_LANE_MAP: 0x3012
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x02
...
---
device:
    0:
        PORT:
            ?
                PORT_ID: 19
            :
                ING_SYSTEM_PORT_TABLE_ID: 19
            ?
                PORT_ID: 59
            :
                ING_SYSTEM_PORT_TABLE_ID: 59
...
---
device:
    0:
        PORT_PROPERTY:
            ?
                PORT_ID: 19
            :
                PORT_TYPE: 1
                PORT_PARSER: 5
                EGR_PORT_PROPERTY: 2
            ?
                PORT_ID: 59
            :
                PORT_TYPE: 1
                PORT_PARSER: 5
                EGR_PORT_PROPERTY: 2
...
---
bcm_device:
    0:
        global:
            pktio_mode: 1
            bcm_tunnel_term_compatible_mode: 1
            vlan_flooding_l2mc_num_reserved: 0
            l3_alpm_template: 1
            l3_alpm2_bnk_threshold: 100
            l2_hitbit_enable: 0
            uft_mode: 1
            l3_enable: 1
            ipv6_lpm_128b_enable: 1
            l3_alpm_hit_skip: 1
            shared_block_mask_section: uc_bc
            skip_protocol_default_entries: 1
            sai_tunnel_support: 1
            multi_network_groups: 1
            sai_fast_convergence_support: 1
            sai_nbr_bcast_ifp_optimized: 1
            flowtracker_enable : 1
            flowtracker_hardware_learn_enable : 2
            flowtracker_flexctr_alloc_enable : 1
            flowtracker_drop_monitor_enable : 1
            sai_mod_mirror_port_pass1_pp_pipe0: 4
            sai_mod_mirror_port_pass1_pp_pipe1: 40
            ipmc_age_mode: 1
            flexctr_action_reserved_ipmc_hitbit: 1
            use_all_splithorizon_groups: 1
            riot_enable: 1
            riot_overlay_l3_intf_mem_size: 8192
            riot_overlay_l3_egress_mem_size: 32768
            l3_ecmp_levels: 2
            riot_overlay_ecmp_resilient_hash_size: 16384
            sai_mmu_mod_queue_number: 3
            sai_feat_tail_timestamp: 1
            sai_port_phy_time_sync_en: 1
            sai_port_queue_ecn_counter: 1
            sai_field_group_auto_prioritize: 1
            sai_verify_incoming_chksum: 0
            sai_egr_mod_reserved_vlan: 99
...
---
bcm_device:
    0:
        port:
            "*":
                encap_mode: IEEE
...
---
device:
    0:
        SER_CONFIG:
            SER_LOG_DEPTH: 10
            SER_ENABLE: 1
            MESSAGE_Q_DEPTH: 8
...
---
device:
    0:
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...
---
device:
        0:
                TM_SCHEDULER_CONFIG:
                        NUM_MC_Q: NUM_MC_Q_4
...
---
component:
    trm_resources:
        max_entries: 32768
...
---
bcm_device:
    0:
        global:
            global_flexctr_ing_action_num_reserved: 32
            global_flexctr_ing_group_num_reserved: 4
            global_flexctr_ing_pool_num_reserved: 20
            global_flexctr_ing_quant_num_reserved: 4
            global_flexctr_ing_op_profile_num_reserved: 10
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 1
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0

        # Per pipe flex state configuration
        #FLEX_STATE_CONFIG:
        #    FLEX_STATE_ING_OPERMODE_PIPEUNIQUE: 0
        #    FLEX_STATE_EGR_OPERMODE_PIPEUNIQUE: 1

        # Lossy vs Lossless mode
        #TM_THD_CONFIG:
        #    THRESHOLD_MODE: LOSSLESS
...
