#
# $Copyright: (c) 2022 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# BCM56995 32x400g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#
---
bcm_device:
    0:
        global:
            pktio_mode: 1
            vlan_flooding_l2mc_num_reserved: 0
            ipv6_lpm_128b_enable: 1
            shared_block_mask_section: uc_bc
            skip_protocol_default_entries: 1
            # LTSW uses value 1 for ALPM combined mode
            l3_alpm_template: 1
            l3_alpm_hit_skip: 1
            sai_feat_tail_timestamp : 1
            sai_field_group_auto_prioritize: 1
            #l3_intf_vlan_split_egress for MTU at L3IF
            l3_intf_vlan_split_egress : 1
            pfc_deadlock_seq_control : 1
            sai_tunnel_support: 2
            bcm_tunnel_term_compatible_mode: 1
            l3_ecmp_member_first_lkup_mem_size: 12288
            sai_port_phy_time_sync_en: 1
            ipmc_age_mode: 1
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x64572301
                TX_LANE_MAP: 0x10327546
                RX_POLARITY_FLIP: 0x1a
                TX_POLARITY_FLIP: 0xf1
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21537460
                TX_LANE_MAP: 0x12456703
                RX_POLARITY_FLIP: 0x0c
                TX_POLARITY_FLIP: 0xd9
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x45637210
                TX_LANE_MAP: 0x75130246
                RX_POLARITY_FLIP: 0x50
                TX_POLARITY_FLIP: 0xcb
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x45637210
                TX_LANE_MAP: 0x75130246
                RX_POLARITY_FLIP: 0x50
                TX_POLARITY_FLIP: 0xcb
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x36572104
                TX_LANE_MAP: 0x56370142
                RX_POLARITY_FLIP: 0xdf
                TX_POLARITY_FLIP: 0x2d
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x36572104
                TX_LANE_MAP: 0x56317042
                RX_POLARITY_FLIP: 0xdf
                TX_POLARITY_FLIP: 0x35
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x16074532
                TX_LANE_MAP: 0x73562401
                RX_POLARITY_FLIP: 0xe1
                TX_POLARITY_FLIP: 0x14
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10324567
                TX_LANE_MAP: 0x57260431
                RX_POLARITY_FLIP: 0xab
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x65723014
                TX_LANE_MAP: 0x04215367
                RX_POLARITY_FLIP: 0x54
                TX_POLARITY_FLIP: 0xff
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x35472610
                TX_LANE_MAP: 0x21507346
                RX_POLARITY_FLIP: 0x14
                TX_POLARITY_FLIP: 0xfb
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10726345
                TX_LANE_MAP: 0x02137564
                RX_POLARITY_FLIP: 0x01
                TX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01372645
                TX_LANE_MAP: 0x03127546
                RX_POLARITY_FLIP: 0x01
                TX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 29
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x45137260
                TX_LANE_MAP: 0x30512746
                RX_POLARITY_FLIP: 0xab
                TX_POLARITY_FLIP: 0xd0
            ?
                PC_PM_ID: 30
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x45137260
                TX_LANE_MAP: 0x30512746
                RX_POLARITY_FLIP: 0xab
                TX_POLARITY_FLIP: 0xd0
            ?
                PC_PM_ID: 31
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x60547321
                TX_LANE_MAP: 0x03654712
                RX_POLARITY_FLIP: 0xf7
                TX_POLARITY_FLIP: 0x54
            ?
                PC_PM_ID: 32
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x01532764
                TX_LANE_MAP: 0x46723510
                RX_POLARITY_FLIP: 0xd7
                TX_POLARITY_FLIP: 0x14
...
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 17
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 18
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 34
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 35
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 51
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 52
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 68
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 69
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 85
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 86
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 102
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 103
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 119
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 120
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 136
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 137
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 153
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 154
            :
                PC_PHYS_PORT_ID: 153
            ?
                PORT_ID: 170
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 171
            :
                PC_PHYS_PORT_ID: 169
            ?
                PORT_ID: 187
            :
                PC_PHYS_PORT_ID: 177
            ?
                PORT_ID: 188
            :
                PC_PHYS_PORT_ID: 185
            ?
                PORT_ID: 204
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 205
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 221
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 222
            :
                PC_PHYS_PORT_ID: 217
            ?
                PORT_ID: 238
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 239
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 255
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 256
            :
                PC_PHYS_PORT_ID: 249
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[1, 2],
                          [17, 18],
                          [34, 35],
                          [51, 52],
                          [68, 69],
                          [85, 86],
                          [102, 103],
                          [119, 120],
                          [136, 137],
                          [153, 154],
                          [170, 171],
                          [187, 188],
                          [204, 205],
                          [221, 222],
                          [238, 239],
                          [255, 256]]
            :
                ENABLE: 0
                SPEED: 400000
                NUM_LANES: 8
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 0
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0

        # Per pipe flex state configuration
        #FLEX_STATE_CONFIG:
        #    FLEX_STATE_ING_OPERMODE_PIPEUNIQUE: 0
        #    FLEX_STATE_EGR_OPERMODE_PIPEUNIQUE: 1

        # Lossy vs Lossless mode
        TM_THD_CONFIG:
            THRESHOLD_MODE: LOSSLESS

        # IFP mode
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...

