# $Copyright: Broadcom Ltd.$
#
# BCM56996 64x400g port configuration.
#
# configuration yaml file
---
bcm_device:
    0:
        #global:
        global:
            pktio_mode: 1
            vlan_flooding_l2mc_num_reserved: 0
            ipv6_lpm_128b_enable: 1
            shared_block_mask_section: uc_bc
            skip_protocol_default_entries: 1
            #sai_tunnel_support: 1
            #bcm_tunnel_term_compatible_mode: 1
            l3_alpm_template: 2
            #riot_overlay_l3_egress_mem_size: 16384
            #riot_overlay_l3_intf_mem_size: 4096
            sai_port_phy_time_sync_en: 1
            sai_field_group_auto_prioritize: 1
            pfc_deadlock_seq_control : 1
            sai_tunnel_support: 2
            bcm_tunnel_term_compatible_mode: 1
            l3_ecmp_member_first_lkup_mem_size: 12288
...
---
device:
    0:
        #DEVICE_CONFIG:

...
---
device:
    0:
        #PC_PM_CORE:
        PC_PM_CORE:
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x76541230
                TX_LANE_MAP: 0x51734260
                RX_POLARITY_FLIP: 0x83
                TX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x76541230
                TX_LANE_MAP: 0x56734210
                RX_POLARITY_FLIP: 0x83
                TX_POLARITY_FLIP: 0x4d
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03764251
                TX_LANE_MAP: 0x01456723
                RX_POLARITY_FLIP: 0xc8
                TX_POLARITY_FLIP: 0xeb
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x73215604
                TX_LANE_MAP: 0x75641032
                RX_POLARITY_FLIP: 0x73
                TX_POLARITY_FLIP: 0x35
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x64201537
                TX_LANE_MAP: 0x75321064
                RX_POLARITY_FLIP: 0x85
                TX_POLARITY_FLIP: 0xe8
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x15742063
                TX_LANE_MAP: 0x01236745
                RX_POLARITY_FLIP: 0x8e
                TX_POLARITY_FLIP: 0x85
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32541670
                TX_LANE_MAP: 0x21405763
                RX_POLARITY_FLIP: 0x7c
                TX_POLARITY_FLIP: 0x4d
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x32541670
                TX_LANE_MAP: 0x21305764
                RX_POLARITY_FLIP: 0x7c
                TX_POLARITY_FLIP: 0x6c

...
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 3
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 7
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 6
            :
                PC_PHYS_PORT_ID: 11
            ?
                PORT_ID: 7
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 8
            :
                PC_PHYS_PORT_ID: 15
            ?
                PORT_ID: 17     # Pipe1
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 18
            :
                PC_PHYS_PORT_ID: 19
            ?
                PORT_ID: 19
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 23
            ?
                PORT_ID: 21     # Pipe1
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 27
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 24
            :
                PC_PHYS_PORT_ID: 31
            ?
                PORT_ID: 34     # Pipe2
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 35
            :
                PC_PHYS_PORT_ID: 35
            ?
                PORT_ID: 36
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 37
            :
                PC_PHYS_PORT_ID: 39
            ?
                PORT_ID: 38     # Pipe2
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 39
            :
                PC_PHYS_PORT_ID: 43
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 47
            ?
                PORT_ID: 51     # Pipe3
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 52
            :
                PC_PHYS_PORT_ID: 51
            ?
                PORT_ID: 53
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 54
            :
                PC_PHYS_PORT_ID: 55
            ?
                PORT_ID: 55     # Pipe3
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 56
            :
                PC_PHYS_PORT_ID: 59
            ?
                PORT_ID: 57
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 58
            :
                PC_PHYS_PORT_ID: 63
            ?
                PORT_ID: 68     # Pipe4
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 69
            :
                PC_PHYS_PORT_ID: 67
            ?
                PORT_ID: 70
            :
                PC_PHYS_PORT_ID: 69
            ?
                PORT_ID: 71
            :
                PC_PHYS_PORT_ID: 71
            ?
                PORT_ID: 72     # Pipe4
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 73
            :
                PC_PHYS_PORT_ID: 75
            ?
                PORT_ID: 74
            :
                PC_PHYS_PORT_ID: 77
            ?
                PORT_ID: 75
            :
                PC_PHYS_PORT_ID: 79
            ?
                PORT_ID: 85     # Pipe5
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 86
            :
                PC_PHYS_PORT_ID: 83
            ?
                PORT_ID: 87
            :
                PC_PHYS_PORT_ID: 85
            ?
                PORT_ID: 88
            :
                PC_PHYS_PORT_ID: 87
            ?
                PORT_ID: 89     # Pipe5
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 90
            :
                PC_PHYS_PORT_ID: 91
            ?
                PORT_ID: 91
            :
                PC_PHYS_PORT_ID: 93
            ?
                PORT_ID: 92
            :
                PC_PHYS_PORT_ID: 95
            ?
                PORT_ID: 102     # Pipe6
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 103
            :
                PC_PHYS_PORT_ID: 99
            ?
                PORT_ID: 104
            :
                PC_PHYS_PORT_ID: 101
            ?
                PORT_ID: 105
            :
                PC_PHYS_PORT_ID: 103
            ?
                PORT_ID: 106     # Pipe6
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 107
            :
                PC_PHYS_PORT_ID: 107
            ?
                PORT_ID: 108
            :
                PC_PHYS_PORT_ID: 109
            ?
                PORT_ID: 109
            :
                PC_PHYS_PORT_ID: 111
            ?
                PORT_ID: 119     # Pipe7
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 120
            :
                PC_PHYS_PORT_ID: 115
            ?
                PORT_ID: 121
            :
                PC_PHYS_PORT_ID: 117
            ?
                PORT_ID: 122
            :
                PC_PHYS_PORT_ID: 119
            ?
                PORT_ID: 123     # Pipe7
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 124
            :
                PC_PHYS_PORT_ID: 123
            ?
                PORT_ID: 125
            :
                PC_PHYS_PORT_ID: 125
            ?
                PORT_ID: 126
            :
                PC_PHYS_PORT_ID: 127
            ?
                PORT_ID: 136     # Pipe8
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 137
            :
                PC_PHYS_PORT_ID: 131
            ?
                PORT_ID: 138
            :
                PC_PHYS_PORT_ID: 133
            ?
                PORT_ID: 139
            :
                PC_PHYS_PORT_ID: 135
            ?
                PORT_ID: 140     # Pipe8
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 141
            :
                PC_PHYS_PORT_ID: 139
            ?
                PORT_ID: 142
            :
                PC_PHYS_PORT_ID: 141
            ?
                PORT_ID: 143
            :
                PC_PHYS_PORT_ID: 143
            ?
                PORT_ID: 153     # Pipe9
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 154
            :
                PC_PHYS_PORT_ID: 147
            ?
                PORT_ID: 155
            :
                PC_PHYS_PORT_ID: 149
            ?
                PORT_ID: 156
            :
                PC_PHYS_PORT_ID: 151
            ?
                PORT_ID: 157     # Pipe9
            :
                PC_PHYS_PORT_ID: 153
            ?
                PORT_ID: 158
            :
                PC_PHYS_PORT_ID: 155
            ?
                PORT_ID: 159
            :
                PC_PHYS_PORT_ID: 157
            ?
                PORT_ID: 160
            :
                PC_PHYS_PORT_ID: 159
            ?
                PORT_ID: 170    # Pipe10
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 171
            :
                PC_PHYS_PORT_ID: 163
            ?
                PORT_ID: 172
            :
                PC_PHYS_PORT_ID: 165
            ?
                PORT_ID: 173
            :
                PC_PHYS_PORT_ID: 167
            ?
                PORT_ID: 174    # Pipe10
            :
                PC_PHYS_PORT_ID: 169
            ?
                PORT_ID: 175
            :
                PC_PHYS_PORT_ID: 171
            ?
                PORT_ID: 176
            :
                PC_PHYS_PORT_ID: 173
            ?
                PORT_ID: 177
            :
                PC_PHYS_PORT_ID: 175
            ?
                PORT_ID: 187    # Pipe11
            :
                PC_PHYS_PORT_ID: 177
            ?
                PORT_ID: 188
            :
                PC_PHYS_PORT_ID: 179
            ?
                PORT_ID: 189
            :
                PC_PHYS_PORT_ID: 181
            ?
                PORT_ID: 190
            :
                PC_PHYS_PORT_ID: 183
            ?
                PORT_ID: 191    # Pipe11
            :
                PC_PHYS_PORT_ID: 185
            ?
                PORT_ID: 192
            :
                PC_PHYS_PORT_ID: 187
            ?
                PORT_ID: 193
            :
                PC_PHYS_PORT_ID: 189
            ?
                PORT_ID: 194
            :
                PC_PHYS_PORT_ID: 191
            ?
                PORT_ID: 204    # Pipe12
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 205
            :
                PC_PHYS_PORT_ID: 195
            ?
                PORT_ID: 206
            :
                PC_PHYS_PORT_ID: 197
            ?
                PORT_ID: 207
            :
                PC_PHYS_PORT_ID: 199
            ?
                PORT_ID: 208    # Pipe12
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 209
            :
                PC_PHYS_PORT_ID: 203
            ?
                PORT_ID: 210
            :
                PC_PHYS_PORT_ID: 205
            ?
                PORT_ID: 211
            :
                PC_PHYS_PORT_ID: 207
            ?
                PORT_ID: 221    # Pipe13
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 222
            :
                PC_PHYS_PORT_ID: 211
            ?
                PORT_ID: 223
            :
                PC_PHYS_PORT_ID: 213
            ?
                PORT_ID: 224
            :
                PC_PHYS_PORT_ID: 215
            ?
                PORT_ID: 225    # Pipe13
            :
                PC_PHYS_PORT_ID: 217
            ?
                PORT_ID: 226
            :
                PC_PHYS_PORT_ID: 219
            ?
                PORT_ID: 227
            :
                PC_PHYS_PORT_ID: 221
            ?
                PORT_ID: 228
            :
                PC_PHYS_PORT_ID: 223
            ?
                PORT_ID: 238    # Pipe14
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 239
            :
                PC_PHYS_PORT_ID: 227
            ?
                PORT_ID: 240
            :
                PC_PHYS_PORT_ID: 229
            ?
                PORT_ID: 241
            :
                PC_PHYS_PORT_ID: 231
            ?
                PORT_ID: 242    # Pipe14
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 243
            :
                PC_PHYS_PORT_ID: 235
            ?
                PORT_ID: 244
            :
                PC_PHYS_PORT_ID: 237
            ?
                PORT_ID: 245
            :
                PC_PHYS_PORT_ID: 239
            ?
                PORT_ID: 255    # Pipe15
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 256
            :
                PC_PHYS_PORT_ID: 243
            ?
                PORT_ID: 257
            :
                PC_PHYS_PORT_ID: 245
            ?
                PORT_ID: 258
            :
                PC_PHYS_PORT_ID: 247
            ?
                PORT_ID: 259    # Pipe15
            :
                PC_PHYS_PORT_ID: 249
            ?
                PORT_ID: 260
            :
                PC_PHYS_PORT_ID: 251
            ?
                PORT_ID: 261
            :
                PC_PHYS_PORT_ID: 253
            ?
                PORT_ID: 262
            :
                PC_PHYS_PORT_ID: 255
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[1, 8],
                          [17, 24],
                          [34, 41],
                          [51, 58],
                          [68, 75],
                          [85, 92],
                          [102, 109],
                          [119, 126],
                          [136, 143],
                          [153, 160],
                          [170, 177],
                          [187, 194],
                          [204, 211],
                          [221, 228],
                          [238, 245],
                          [255, 262]]
            :
                ENABLE: 1
                SPEED: 200000
                NUM_LANES: 2
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 0
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0

        # Per pipe flex state configuration
        #FLEX_STATE_CONFIG:
        #    FLEX_STATE_ING_OPERMODE_PIPEUNIQUE: 0
        #    FLEX_STATE_EGR_OPERMODE_PIPEUNIQUE: 1

        # Lossy vs Lossless mode
        TM_THD_CONFIG:
            THRESHOLD_MODE: LOSSLESS

        # IFP mode
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...
