# $Copyright: Broadcom Ltd.$
#
# BCM56993 32x400g port configuration.
# Support pipe numbers: 0, 1, 2, 3, 12, 13, 14, 15
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
bcm_device:
    0:
        #global:
        global:
            pktio_mode: 1
            vlan_flooding_l2mc_num_reserved: 0
            ipv6_lpm_128b_enable: 1
            shared_block_mask_section: uc_bc
            skip_protocol_default_entries: 1
            #sai_tunnel_support: 1
            #bcm_tunnel_term_compatible_mode: 1
            # LTSW uses value 1 for ALPM combined mode
            l3_alpm_template: 1
            riot_overlay_l3_egress_mem_size: 16384
            riot_overlay_l3_intf_mem_size: 4096
            sai_port_phy_time_sync_en: 1
            sai_feat_tail_timestamp : 1
            sai_acl_qset_optimization: 0
            sai_field_group_auto_prioritize: 1
            #l3_intf_vlan_split_egress for MTU at L3IF
            l3_intf_vlan_split_egress : 1
            l3_alpm_hit_skip : 1
            pfc_deadlock_seq_control : 1
            sai_tunnel_support: 10
            bcm_tunnel_term_compatible_mode: 1
            l3_ecmp_member_first_lkup_mem_size: 12288
            shared_l2_tunnel: 1
            #enable only P2MP Test Cases
            sai_tunnel_underlay_route_mode: 2
            sai_tunnel_ecmp_sharing_mode: 2
            sai_fast_convergence_support: 1
            bfd_enable: 1
            bfd_sha1_keys: 5
            bfd_num_sessions: 4096
            bfd_simple_password_keys: 5
            num_queues_pci: 47
            num_queues_uc0: 1
            bfd_feature_enable: 1
            bfd_use_endpoint_id_as_discriminator: 1
            bfd_tx_raw_ingress_enable: 1
            sai_eapp_config_file: "/tmp/eapp_config.json"
            #Set bit mask to enable port queue drop stats  @ref _BRCM_SAI_STATS_SUPPORT_MASK. 
            #Bits: RouteStats:2, QueueDrops:1 RifCounter:0
            sai_stats_support_mask: 6
            #Set resources for counters in global mode counters like ACL, etc 
            global_flexctr_ing_action_num_reserved: 20
            global_flexctr_ing_pool_num_reserved: 8
            global_flexctr_ing_op_profile_num_reserved: 20
            global_flexctr_ing_group_num_reserved: 1
            global_flexctr_egr_action_num_reserved: 8
            global_flexctr_egr_pool_num_reserved: 5
            global_flexctr_egr_op_profile_num_reserved: 10
            global_flexctr_egr_group_num_reserved: 1
            ipmc_age_mode: 1
...
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 17
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 18
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 19
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 34
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 35
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 36
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 37
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 51
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 52
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 53
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 54
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 204
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 205
            :
                PC_PHYS_PORT_ID: 197
            ?
                PORT_ID: 206
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 207
            :
                PC_PHYS_PORT_ID: 205
            ?
                PORT_ID: 221
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 222
            :
                PC_PHYS_PORT_ID: 213
            ?
                PORT_ID: 223
            :
                PC_PHYS_PORT_ID: 217
            ?
                PORT_ID: 224
            :
                PC_PHYS_PORT_ID: 221
            ?
                PORT_ID: 238
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 239
            :
                PC_PHYS_PORT_ID: 229
            ?
                PORT_ID: 240
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 241
            :
                PC_PHYS_PORT_ID: 237
            ?
                PORT_ID: 255
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 256
            :
                PC_PHYS_PORT_ID: 245
            ?
                PORT_ID: 257
            :
                PC_PHYS_PORT_ID: 249
            ?
                PORT_ID: 258
            :
                PC_PHYS_PORT_ID: 253
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: [[1, 4],
                          [17, 20],
                          [34, 37],
                          [51, 54],
                          [204, 207],
                          [221, 224],
                          [238, 241],
                          [255, 258]]
            :
                ENABLE: 0
                SPEED: 400000
                NUM_LANES: 8
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 1
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 1
            CTR_ING_EFLEX_OPERMODE_PIPE_INSTANCE_UNIQUE: 1
            CTR_EGR_EFLEX_OPERMODE_PIPE_INSTANCE_UNIQUE: 1

        # Lossy vs Lossless mode
        TM_THD_CONFIG:
            THRESHOLD_MODE: LOSSLESS

        # IFP mode
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...
---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40615372
                TX_LANE_MAP: 0x67315204
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0xfd
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67241053
                TX_LANE_MAP: 0x04715362
                RX_POLARITY_FLIP: 0xe8
                TX_POLARITY_FLIP: 0x35
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x23451706
                TX_LANE_MAP: 0x30571246
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x47
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x46532071
                TX_LANE_MAP: 0x67210435
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xaf
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47025631
                TX_LANE_MAP: 0x02641375
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x0b
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40675123
                TX_LANE_MAP: 0x64037512
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0x15
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47035621
                TX_LANE_MAP: 0x12760354
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x82
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x02573146
                TX_LANE_MAP: 0x75126403
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x4c
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03471265
                TX_LANE_MAP: 0x65017423
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xed
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x57034612
                TX_LANE_MAP: 0x03741265
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0xe8
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03471265
                TX_LANE_MAP: 0x65017423
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xed
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67402351
                TX_LANE_MAP: 0x03741265
                RX_POLARITY_FLIP: 0x95
                TX_POLARITY_FLIP: 0xe8
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10675423
                TX_LANE_MAP: 0x53216704
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xe3
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x35062417
                TX_LANE_MAP: 0x03471256
                RX_POLARITY_FLIP: 0x00
                TX_POLARITY_FLIP: 0x01
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21453076
                TX_LANE_MAP: 0x60125743
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xbb
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21573046
                TX_LANE_MAP: 0x67135204
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xfc
            ?
                PC_PM_ID: 49
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x12573046
                TX_LANE_MAP: 0x46017523
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xdb
            ?
                PC_PM_ID: 50
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21563047
                TX_LANE_MAP: 0x57306412
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x4f
            ?
                PC_PM_ID: 51
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x53102467
                TX_LANE_MAP: 0x02571364
                RX_POLARITY_FLIP: 0x21
                TX_POLARITY_FLIP: 0x2c
            ?
                PC_PM_ID: 52
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x10675423
                TX_LANE_MAP: 0x27056413
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0xfa
            ?
                PC_PM_ID: 53
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x67402351
                TX_LANE_MAP: 0x20761453
                RX_POLARITY_FLIP: 0x95
                TX_POLARITY_FLIP: 0x98
            ?
                PC_PM_ID: 54
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03572146
                TX_LANE_MAP: 0x76205314
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x99
            ?
                PC_PM_ID: 55
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x57034612
                TX_LANE_MAP: 0x20751463
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x98
            ?
                PC_PM_ID: 56
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x03572146
                TX_LANE_MAP: 0x76205314
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x99
            ?
                PC_PM_ID: 57
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21573046
                TX_LANE_MAP: 0x57026413
                RX_POLARITY_FLIP: 0xaa
                TX_POLARITY_FLIP: 0x6d
            ?
                PC_PM_ID: 58
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47136502
                TX_LANE_MAP: 0x01572463
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x24
            ?
                PC_PM_ID: 59
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40675123
                TX_LANE_MAP: 0x57026314
                RX_POLARITY_FLIP: 0x9a
                TX_POLARITY_FLIP: 0x7f
            ?
                PC_PM_ID: 60
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x47136502
                TX_LANE_MAP: 0x02761453
                RX_POLARITY_FLIP: 0x55
                TX_POLARITY_FLIP: 0x7e
            ?
                PC_PM_ID: 61
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x54126073
                TX_LANE_MAP: 0x65124703
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x5f
            ?
                PC_PM_ID: 62
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x73062415
                TX_LANE_MAP: 0x01472365
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x00
            ?
                PC_PM_ID: 63
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x21643075
                TX_LANE_MAP: 0x17520436
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0xa9
            ?
                PC_PM_ID: 64
                CORE_INDEX: 0
            :
                RX_LANE_MAP_AUTO: 0
                TX_LANE_MAP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_LANE_MAP: 0x40735162
                TX_LANE_MAP: 0x57130624
                RX_POLARITY_FLIP: 0xff
                TX_POLARITY_FLIP: 0x28
...
