[package]
name = "xcvr"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8.1"
thiserror = "1.0.49"
xcvr-sys = { version = "0.1.7", path = "../xcvr-sys" }
