[package]
name = "onie-said"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
ipnet = "2.8.0"
log = "0.4.20"
sai = { version = "0.1.0", path = "../sai" }
