[package]
name = "sai-sys"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69.1"

[dependencies]
ipnet = "2.8.0"
