---
    name: Continuous Integration
    on:
      pull_request:
      push:
        branches:
          - main
        tags:
          - "*"
      # schedule:
      #   - cron: "0 10 * * *" # ~2am PST
      workflow_dispatch:
        inputs:
          debug_enabled:
            type: boolean
            description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
            required: false
            default: false
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true
    jobs:
      build:
        # env:
        #   GOPRIVATE: go.githedgehog.com
        #   GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Install dependencies
            run: make init
          - name: Run build
            run: make build
          - name: Setup tmate session for debug
            if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
            uses: mxschmitt/action-tmate@v3
            timeout-minutes: 30
            with:
              limit-access-to-actor: true
