---
    name: Build and Release on git tags
    on:
      push:
        tags:
          - "*"
      workflow_dispatch:
        inputs:
          debug_enabled:
            type: boolean
            description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
            required: false
            default: false
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
      cancel-in-progress: true
    jobs:
      build:
        # env:
        #   GOPRIVATE: go.githedgehog.com
        #   GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Install dependencies
            run: make init
          - name: Run build
            run: make build
          - name: Create packages
            run: make package
          - name: Upload packages as build artifacts
            uses: actions/upload-artifact@v3
            with:
              name: packages
              path: |
                artifacts
                !artifacts/.keepme
          - name: Setup tmate session for debug
            if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
            uses: mxschmitt/action-tmate@v3
            timeout-minutes: 30
            with:
              limit-access-to-actor: true
      publish:
        name: Publish to GitHub Packages
        if: startsWith(github.event.ref, 'refs/tags/') && github.event_name == 'push'
        runs-on: ubuntu-latest
        needs:
          - build
        # env:
        #   GOPRIVATE: go.githedgehog.com
        #   GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        steps:
          - name: Download packages from build job
            uses: actions/download-artifact@v3
            with:
              name: packages
          - name: Release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
              files: onie-*.tar.*
          - name: Setup tmate session for debug
            if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
            uses: mxschmitt/action-tmate@v3
            timeout-minutes: 30
            with:
              limit-access-to-actor: true